vendor:
    name:       ru-tld
    title:      RU-TLD
    homepage:   https://ru-tld.ru/
    forum:      https://ru-tld.ru/
    email:      support@ru-tld.ru
    authors:
        hiqsol:
            name:       Andrii Vasyliev
            role:       Project lead
            email:      sol@hiqdev.com
            github:     https://github.com/hiqsol
            homepage:   http://hipanel.com/
