vendor:
    name:       ru-tld
    title:      RU-TLD
    homepage:   https://ru-tld.ru/
    forum:      https://ru-tld.ru/
    email:      support@ru-tld.ru
    authors:
        hiqsol:
            name:       Andrii Vasyliev
            role:       Project lead
            email:      sol@hiqdev.com
            github:     https://github.com/hiqsol
            homepage:   http://hipanel.com/

php-cs-fixer:
    header: |
        {{ config.package.title }}

        @link      {{ config.package.homepage }}
        @package   {{ config.package.name }}
        @license   {{ config.package.license }}
        @copyright Copyright (c) {{ config.package.years }}, {{ config.vendor.titleAndHomepage }}
    fixers:
        'header_comment':   'Add, replace or remove header comment.'
    finder:
        notPath:
            - vendor
            - runtime
            - web/assets
