package:
    type:           yii2-extension
    name:           hidev-ru-tld
    title:          RU-TLD vendor configuration for HiDev
    headline:       HiDev RU-TLD
    keywords:       ru-tld, hidev, vendor, config
    namespace:      rutld\hidev\rutld
    description:    |
        [HiDev](https://github.com/hiqdev/hidev) is a task runner, code generator and build tool for easier continuos integration.

        This plugin provides [RU-TLD](https://github.com/ru-tld) vendor configuration for HiDev.
        Used for RU-TLD packages.

        Provides RU-TLD information and settings:

        - general data: vendor name and company title
        - contact data: email, forum, github page
        - authors data: names, roles, emails, github and home pages

        See [src/config/goals.yml](src/config/goals.yml).

include:
    - src/config/goals.yml
